# Default values for postgres-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: crunchydata/postgres-operator
  pullPolicy: IfNotPresent

env:
  debug: "true"
  ccp_image_prefix: "crunchydata"
  ccp_image_tag: "centos7-11.5-2.4.2"
  co_image_prefix: "crunchydata"
  co_image_tag: "centos7-3.5.5"
  tls_no_verify: false

pgo:
  PrimaryStorage: hostpathstorage
  XlogStorage: hostpathstorage
  BackupStorage: hostpathstorage
  ReplicaStorage: hostpathstorage
  BackrestStorage: backreststorage
  Storage:
    hostpathstorage:
      AccessMode: ReadWriteOnce
      Size: 1G
      StorageType: create
    backreststorage:
      AccessMode: ReadWriteOnce
      Size: 1G
      StorageType: create

service:
  type: ClusterIP
  port: 8443

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

serviceAccount:
  name: "postgres-operator"
  create: "true"

rbac:
  create: "true"

nameOverride: "pgo"
